version: '3.3'
networks:
  yolo_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yolo_backend:v1.0
    container_name: yolo_backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    networks:
      - yolo_network
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: yolo_client:v1.0
    container_name: yolo_client
    ports:
      - '3000:3000'
    networks:
      - yolo_network
    stdin_open: true

