version: '3.3'
networks:
  yolo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

services:
  db:
    container_name: yolo_mongodb
    build:
      context: ./backend
      dockerfile: DockerfileMongo
    image: kangangi/yolo_mongo_db:v1.0
    ports:
      - '27017:27017'
    networks:
      - yolo_network
    volumes:
      - mongodb_data:/data/db

  backend:

    build:
      context: ./backend
      dockerfile: DockerfileNode
    environment:
      - MONGO_URI=mongodb://db:27017/yolomy
    image: kangangi/yolo_backend:v1.1
    container_name: yolo_backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    networks:
      - yolo_network
    depends_on:
      - db
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kangangi/yolo_client:v1.3
    container_name: yolo_client
    ports:
      - '3000:3000'
    networks:
      - yolo_network
    stdin_open: true

