- name: Create a Yolomy data volume
  docker_volume:
    name: yolomy_volume
    state: present


- name: Create a Yolomy network
  docker_network:
    name: yolomy_network
    state: present
    attachable: true
