---
- name: Install Prerequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository 
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Change User Permissions
  shell: "usermod -aG docker vagrant"