- name: Create a Yolomy data volume
  docker_volume:
    name: yolomy_volume
    state: present


- name: Create a Yolomy network
  docker_network:
    name: yolomy_network
    state: present
    attachable: true


- name: Pull client image from repository
  docker_image:
    name: kangangi/yolo_client:v1.3
    source: pull

- name: Pull backend image from repository
  docker_image:
    name: kangangi/yolo_backend:v1.1
    source: pull

- name: Pull mongodb image from repository
  docker_image:
    name: mongo:latest
    source: pull


- name: Run React Client App Container
  docker_container:
    name: yolo_client_container
    image: kangangi/yolo_client:v1.3
    state: started
    ports: 
      - '3000:3000'
    networks:
      - name: yolomy_network
    restart_policy: always
    tty: yes


- name: Run Mongo DB Container
  docker_container:
    name: yolo_mongo_db_container
    image: mongo:latest
    state: started
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - name: yolomy_network


- name: Wait for MongoDB to be ready
  wait_for:
    port: 27017
    timeout: 60

- name: Run Node Container
  docker_container:
    name: yolo_backend_container
    image: kangangi/yolo_backend:v1.1
    state: started
    env :
      MONGO_URI: mongodb://db:27017/yolomy
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    networks:
      - name: yolomy_network
    links:
      - yolo_mongo_db_container:db


