
- name: Create a Yolomy network
  docker_network:
    name: "{{ network }}"
    state: present
    attachable: true


- name: Pull client image from repository
  docker_image:
    name: kangangi/yolo_client:v1.3
    source: pull

- name: Pull backend image from repository
  docker_image:
    name: kangangi/yolo_backend:v1.1
    source: pull

- name: Pull mongodb image from repository
  docker_image:
    name: mongo:latest
    source: pull


- name: Run React Client App Container
  docker_container:
    name: "{{ frontend }}"
    image: kangangi/yolo_client:v1.3
    state: started
    ports: 
      - '3000:3000'
    networks:
      - name: "{{ network }}"
    restart_policy: always
    tty: yes


- name: Run Mongo DB Container
  docker_container:
    name: "{{ db }}"
    image: mongo:latest
    state: started
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - name: "{{ network }}"


- name: Wait for MongoDB to be ready
  wait_for:
    port: 27017
    timeout: 60

- name: Run Node Container
  docker_container:
    name: "{{ backend }}"
    image: kangangi/yolo_backend:v1.1
    state: started
    env :
      MONGO_URI: mongodb://db:27017/yolomy
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    networks:
      - name: "{{ network }}"
    links:
      - "{{ db }}:db"


